[package]
name = "oat"
version = "0.1.1"
description = "A chess engine"
edition = "2021"
repository = "https://github.com/clfs/oat"
authors = ["Calvin Figuereo-Supraner <mail@calvin.page>"]
readme = "README.md"
license = "MIT"

[dependencies]
vampirc-uci = "0.11"