[package]
name = "aloe"
version = "0.1.0"
description = "A chess engine"
edition = "2021"
repository = "https://github.com/clfs/aloe"
authors = ["Calvin Figuereo-Supraner <mail@calvin.page>"]
readme = "README.md"
license = "MIT"
publish = false

[dependencies]
