name: Build, lint, and test with Cargo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and test on latest
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Compile
        run: cargo build --verbose

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        run: cargo test --verbose
